//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Sex { get; set; }
        public System.DateTime DOB { get; set; }
        public string Epgm { get; set; }
        public Nullable<int> Degree { get; set; }
        public Nullable<int> VaChapter { get; set; }
        public string HomeAdress { get; set; }
        public string City { get; set; }
        public string HomeState { get; set; }
        public string ZipCode { get; set; }
        public string PhoneNumber { get; set; }
        public string AltPhone { get; set; }
        public string Email { get; set; }
    
        public virtual DegreeTitle DegreeTitle { get; set; }
        public virtual VaChapter VaChapter1 { get; set; }

    }
}
